// Generated by gencpp from file ros_referee/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_REFEREE_MESSAGE_ADDTWOINTS_H
#define ROS_REFEREE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_referee/AddTwoIntsRequest.h>
#include <ros_referee/AddTwoIntsResponse.h>


namespace ros_referee
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_referee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_referee::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_referee::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_referee::AddTwoInts > {
  static const char* value()
  {
    return "ros_referee/AddTwoInts";
  }

  static const char* value(const ::ros_referee::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_referee::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_referee::AddTwoInts >
template<>
struct MD5Sum< ::ros_referee::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_referee::AddTwoInts >::value();
  }
  static const char* value(const ::ros_referee::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_referee::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_referee::AddTwoInts >
template<>
struct DataType< ::ros_referee::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_referee::AddTwoInts >::value();
  }
  static const char* value(const ::ros_referee::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_referee::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_referee::AddTwoInts >
template<>
struct MD5Sum< ::ros_referee::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_referee::AddTwoInts >::value();
  }
  static const char* value(const ::ros_referee::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_referee::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_referee::AddTwoInts >
template<>
struct DataType< ::ros_referee::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_referee::AddTwoInts >::value();
  }
  static const char* value(const ::ros_referee::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_REFEREE_MESSAGE_ADDTWOINTS_H
